# This workflow uses the release-please GitHub Action to automate releases.
# it only works on the main branch: PR mereged to main will trigger the release-please action
# and PR will be created to update the version in the manifest file and create a release with the new version.
name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Force release version, e.g. 2026.8.0"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.MIDEA_GITHUB_PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          release-as: ${{ inputs.version }}
